import { useState, useEffect } from 'react';
import { useParams, Link, useNavigate } from 'react-router-dom';
import { api } from '../services/api.js';
import {
  Shield, ArrowLeft, FileText, CheckCircle, Download,
  Loader2, Save, AlertCircle, User, DollarSign, Globe,
  AlertTriangle, Clock, ChevronDown, ChevronRight, Code
} from 'lucide-react';

const COUNTRY_COLORS = 'bg-gray-100 text-gray-700 border-gray-200';

function getIndicatorDescription(description) {
  if (description?.startsWith('ML model probability: 0/100')) {
    return 'The model found no strong suspicious pattern in these transactions.';
  }
  if (description?.startsWith('Model classification:')) {
    return description.replace('Model classification:', 'The model assessment is:');
  }
  if (description?.startsWith('Top model features:')) {
    return `The model mainly considered ${description.replace('Top model features:', '').trim().replaceAll('_', ' ')}.`;
  }
  return description;
}

export default function CaseDetailPage() {
  const { caseId } = useParams();
  const navigate = useNavigate();
  const [activeTab, setActiveTab] = useState('data');
  const [loading, setLoading] = useState(true);
  const [caseData, setCaseData] = useState(null);
  const [draft, setDraft] = useState('');
  const [originalDraft, setOriginalDraft] = useState('');
  const [isEditing, setIsEditing] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [isCompleting, setIsCompleting] = useState(false);
  const [expandedLogs, setExpandedLogs] = useState(new Set());

  const fetchCaseData = async () => {
    setLoading(true);
    try {
      const result = await api.getCase(caseId);
      if (result.success && result.data) {
        setCaseData(result.data);
        if (result.data.draft) {
          setDraft(result.data.draft.narrative_text);
          setOriginalDraft(result.data.draft.narrative_text);
        }
      }
    } catch (err) {
      console.error('Error fetching case:', err);
      alert('Failed to load case data: ' + err.message);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { fetchCaseData(); }, [caseId]);

  const handleSave = async () => {
    setIsSaving(true);
    try {
      const newVersion = (Number(caseData.draft?.version_number || 1) + 0.1).toFixed(1);
      await api.saveDraft(caseId, { narrative_text: draft, version_number: parseFloat(newVersion) });
      setOriginalDraft(draft);
      setIsEditing(false);
      await fetchCaseData();
      alert('Draft saved successfully!');
    } catch (err) {
      alert('Failed to save draft: ' + err.message);
    } finally {
      setIsSaving(false);
    }
  };

  const handleMarkAsHandled = async () => {
    if (!confirm('Mark this case as COMPLETED? This action is permanent.')) return;
    setIsCompleting(true);
    try {
      await api.updateCase(caseId, { status: 'COMPLETED', action: 'complete_case' });
      alert('✅ Case marked as COMPLETED successfully!');
      navigate('/dashboard');
    } catch (err) {
      alert('Failed to mark case as completed: ' + err.message);
    } finally {
      setIsCompleting(false);
    }
  };

  const handleDownload = () => {
    const text = `SUSPICIOUS ACTIVITY REPORT (SAR)\nCase ID: ${caseId}\nGenerated: ${new Date().toLocaleString('en-IN')}\n\n${draft}\n\n---\nThis report was generated by AutoSAR AI System v2.0\nFor: Financial Intelligence Unit - India (FIU-IND)\nUnder: Prevention of Money Laundering Act (PMLA) 2002`;
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `SAR_${caseId}_${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const toggleLog = (logId) => {
    const next = new Set(expandedLogs);
    if (next.has(logId)) next.delete(logId); else next.add(logId);
    setExpandedLogs(next);
  };

  if (loading) return (
    <div className="min-h-screen bg-gray-50 flex items-center justify-center">
      <Loader2 className="h-8 w-8 animate-spin text-blue-700" />
      <span className="ml-3 text-gray-600">Loading case...</span>
    </div>
  );

  if (!caseData) return (
    <div className="min-h-screen bg-gray-50 flex items-center justify-center">
      <div className="text-center">
        <AlertCircle className="h-12 w-12 text-red-600 mx-auto mb-4" />
        <p className="text-gray-600">Case not found</p>
        <Link to="/dashboard"><button className="mt-4 px-4 py-2 bg-blue-700 text-white rounded-md text-sm">Back to Dashboard</button></Link>
      </div>
    </div>
  );

  const { case: caseRow, data, ruleOutput, draft: draftRecord, auditLogs } = caseData;
  const canEdit = caseRow.status !== 'COMPLETED' && caseRow.status !== 'APPROVED';
  const riskScore = parseFloat(ruleOutput?.aggregated_risk_score) || 0;
  const riskClass = riskScore >= 80 ? 'text-red-600' : riskScore >= 60 ? 'text-orange-600' : 'text-yellow-600';

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <header className="bg-white border-b border-gray-200 sticky top-0 z-10">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-4">
              <Link to="/dashboard">
                <button className="inline-flex items-center px-3 py-2 border border-gray-300 rounded-md text-sm font-medium text-gray-700 bg-white hover:bg-gray-50">
                  <ArrowLeft className="mr-2 h-4 w-4" /> Back
                </button>
              </Link>
              <div className="h-8 w-px bg-gray-300" />
              <div className="flex items-center space-x-3">
                <Shield className="h-6 w-6 text-blue-700" />
                <div>
                  <h1 className="text-xl font-semibold text-gray-900">{caseId}</h1>
                  <p className="text-sm text-gray-500">{data?.customer_profile?.full_name}</p>
                </div>
              </div>
            </div>
            <div className="flex items-center space-x-3">
              <button onClick={handleDownload} className="inline-flex items-center px-3 py-2 border border-gray-300 rounded-md text-sm font-medium text-gray-700 bg-white hover:bg-gray-50">
                <Download className="mr-2 h-4 w-4" /> Download Report
              </button>
              <span className={`inline-flex items-center px-3 py-1 rounded-full text-sm font-medium ${caseRow.status === 'COMPLETED' ? 'bg-green-100 text-green-800' : caseRow.status === 'UNDER_REVIEW' || caseRow.status === 'Pending Review' ? 'bg-amber-100 text-amber-800' : 'bg-blue-100 text-blue-800'}`}>
                {caseRow.status?.replace(/_/g, ' ')}
              </span>
              <div className="text-sm">
                <span className="text-gray-600">Risk: </span>
                <span className={`font-bold text-lg ${riskClass}`}>{riskScore}</span>
                <span className="text-gray-400">/100</span>
              </div>
            </div>
          </div>

          {/* Tabs */}
          <div className="mt-4 border-b border-gray-200 -mb-px">
            <nav className="flex space-x-8">
              {[
                { id: 'data', label: 'Case Data', icon: User },
                { id: 'draft', label: 'SAR Draft', icon: FileText },
                { id: 'audit', label: 'Audit Trail', icon: ClockIcon },
              ].map(({ id, label, icon: Icon }) => (
                <button key={id} onClick={() => setActiveTab(id)}
                  className={`pb-4 px-1 border-b-2 font-medium text-sm flex items-center ${activeTab === id ? 'border-blue-700 text-blue-700' : 'border-transparent text-gray-500 hover:text-gray-700'}`}>
                  <Icon className="mr-2 h-4 w-4" />{label}
                </button>
              ))}
            </nav>
          </div>
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* ── Case Data Tab ── */}
        {activeTab === 'data' && (
          <div className="space-y-6">
            {/* Customer Profile */}
            <div className="bg-white rounded-lg shadow-sm border border-gray-200">
              <div className="px-6 py-4 border-b border-gray-200 bg-gray-50">
                <h2 className="text-lg font-semibold text-gray-900 flex items-center">
                  <User className="mr-2 h-5 w-5 text-blue-700" /> Customer Profile
                </h2>
              </div>
              <div className="px-6 py-5">
                <dl className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-x-6 gap-y-4">
                  {[
                    ['Full Name', data?.customer_profile?.full_name || 'Unknown'],
                    ['Customer ID', data?.customer_profile?.customer_id || 'Unknown'],
                    ['Risk Rating', data?.customer_profile?.risk_rating || 'Unknown'],
                    ['Occupation', data?.customer_profile?.occupation || 'Unknown'],
                    ['PAN', data?.customer_profile?.pan || 'N/A'],
                    ['Address', data?.customer_profile?.address || 'N/A'],
                  ].map(([label, value]) => (
                    <div key={label} className="space-y-1">
                      <dt className="text-xs font-medium text-gray-500 uppercase tracking-wider">{label}</dt>
                      <dd className="text-sm font-medium text-gray-900">{value}</dd>
                    </div>
                  ))}
                </dl>
              </div>
            </div>

            {/* Transaction Summary */}
            {data?.transaction_summary && (
              <div className="bg-gradient-to-br from-blue-50 to-indigo-50 rounded-lg border border-blue-200 p-6">
                <h3 className="text-sm font-semibold text-gray-900 mb-4">Transaction Summary</h3>
                <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                  {[
                    ['Total Amount', `₹${(data.transaction_summary.total_amount || 0).toLocaleString()}`],
                    ['Count', data.transaction_summary.transaction_count || 0],
                    ['Average', `₹${(data.transaction_summary.average_amount || 0).toLocaleString()}`],
                    ['Risk Score', `${riskScore}/100`],
                  ].map(([label, value]) => (
                    <div key={label}>
                      <p className="text-xs text-gray-600 mb-1">{label}</p>
                      <p className="text-xl font-bold text-gray-900">{value}</p>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Transactions Table */}
            <div className="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden">
              <div className="px-6 py-4 border-b border-gray-200 bg-gray-50">
                <h2 className="text-lg font-semibold text-gray-900 flex items-center">
                  <DollarSign className="mr-2 h-5 w-5 text-blue-700" />
                  Suspicious Transactions ({(data?.transaction_list || []).length})
                </h2>
              </div>
              <div className="overflow-x-auto">
                <table className="min-w-full divide-y divide-gray-200">
                  <thead className="bg-gray-50">
                    <tr>
                      {['Transaction ID','Date','Amount','Counterparty','Country','Type'].map(h => (
                        <th key={h} className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">{h}</th>
                      ))}
                    </tr>
                  </thead>
                  <tbody className="bg-white divide-y divide-gray-200">
                    {(data?.transaction_list || []).map((txn, i) => {
                      return (
                        <tr key={txn.transaction_id || i} className="hover:bg-gray-50">
                          <td className="px-6 py-4 whitespace-nowrap text-sm font-mono text-gray-900">{txn.transaction_id}</td>
                          <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-600">
                            <div className="flex items-center"><Clock className="h-4 w-4 mr-1.5 text-gray-400" />{new Date(txn.date).toLocaleDateString()}</div>
                          </td>
                          <td className="px-6 py-4 whitespace-nowrap text-sm font-bold text-gray-900">{txn.currency} {parseFloat(txn.amount).toLocaleString()}</td>
                          <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">{txn.counterparty}</td>
                          <td className="px-6 py-4 whitespace-nowrap">
                            <div className="flex items-center">
                              <Globe className="h-4 w-4 mr-2 text-gray-400" />
                              <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium border ${COUNTRY_COLORS}`}>
                                {txn.counterparty_country}
                              </span>
                            </div>
                          </td>
                          <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-600">{txn.type}</td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            </div>

            {/* Risk Indicators */}
            {(data?.risk_indicators || []).length > 0 && (
              <div className="bg-white rounded-lg shadow-sm border border-gray-200">
                <div className="px-6 py-4 border-b border-gray-200 bg-red-50">
                  <h2 className="text-lg font-semibold text-gray-900 flex items-center">
                    <AlertTriangle className="mr-2 h-5 w-5 text-red-600" /> Risk Indicators ({data.risk_indicators.length})
                  </h2>
                </div>
                <div className="px-6 py-4">
                  <ul className="space-y-3">
                    {data.risk_indicators.map((ind, i) => {
                      const severity = riskScore >= 75 ? 'CRITICAL' : riskScore >= 50 ? 'HIGH' : riskScore >= 25 ? 'MEDIUM' : 'LOW';
                      const sevColor = severity === 'CRITICAL' ? 'bg-red-100 text-red-800 border-red-300' : severity === 'HIGH' ? 'bg-orange-100 text-orange-800 border-orange-300' : severity === 'MEDIUM' ? 'bg-yellow-100 text-yellow-800 border-yellow-300' : 'bg-gray-100 text-gray-700 border-gray-300';
                      return (
                        <li key={i} className="flex items-start">
                          <span className={`flex-shrink-0 mt-0.5 mr-3 px-2 py-0.5 rounded text-xs font-medium border ${sevColor}`}>{severity}</span>
                          <div>
                            <p className="text-sm font-medium text-gray-900">{ind.indicator_type === 'Rule Violation' ? 'Model assessment' : ind.indicator_type}</p>
                            <p className="text-sm text-gray-600 mt-0.5">{getIndicatorDescription(ind.description)}</p>
                          </div>
                        </li>
                      );
                    })}
                  </ul>
                </div>
              </div>
            )}
          </div>
        )}

        {/* ── SAR Draft Tab ── */}
        {activeTab === 'draft' && (
          <div className="bg-white rounded-lg shadow-sm border border-gray-200">
            <div className="px-6 py-4 border-b border-gray-200 bg-gray-50 flex items-center justify-between">
              <div>
                <h2 className="text-lg font-semibold text-gray-900 flex items-center">
                  <FileText className="mr-2 h-5 w-5 text-blue-700" /> SAR Narrative
                </h2>
                <p className="text-sm text-gray-500 mt-1">
                  Version {parseFloat(draftRecord?.version_number || 1).toFixed(1)}
                  {isEditing && <span className="text-blue-600 ml-2">(Editing...)</span>}
                </p>
              </div>
              <div className="flex items-center space-x-2">
                {canEdit && !isEditing && (
                  <button onClick={() => setIsEditing(true)}
                    className="px-3 py-2 border border-gray-300 rounded-md text-sm font-medium text-gray-700 hover:bg-gray-50">
                    Edit Draft
                  </button>
                )}
                {isEditing && (
                  <button onClick={() => { setDraft(originalDraft); setIsEditing(false); }}
                    className="px-3 py-2 border border-gray-300 rounded-md text-sm font-medium text-gray-700 hover:bg-gray-50">
                    Cancel
                  </button>
                )}
              </div>
            </div>
            <div className="px-6 py-6">
              {isEditing ? (
                <textarea value={draft} onChange={e => setDraft(e.target.value)}
                  className="w-full min-h-[600px] text-sm leading-relaxed font-mono border border-gray-300 rounded-md p-4 focus:outline-none focus:ring-2 focus:ring-blue-500" />
              ) : (
                <div className="whitespace-pre-wrap text-sm text-gray-800 leading-relaxed font-mono bg-gray-50 p-6 rounded border border-gray-200 min-h-[300px]">
                  {draft || 'No draft available'}
                </div>
              )}
            </div>
            <div className="px-6 py-4 border-t border-gray-200 bg-gray-50 flex justify-between items-center">
              <p className="text-sm text-gray-500">{!canEdit && 'Case is completed – editing disabled'}</p>
              <div className="flex space-x-3">
                {isEditing ? (
                  <button onClick={handleSave} disabled={isSaving}
                    className="inline-flex items-center px-4 py-2 bg-blue-700 text-white rounded-md text-sm font-medium hover:bg-blue-800 disabled:opacity-50">
                    {isSaving ? <><Loader2 className="mr-2 h-4 w-4 animate-spin" /> Saving...</> : <><Save className="mr-2 h-4 w-4" /> Save Draft</>}
                  </button>
                ) : (
                  canEdit && (
                    <button onClick={handleMarkAsHandled} disabled={isCompleting}
                      className="inline-flex items-center px-4 py-2 bg-green-700 text-white rounded-md text-sm font-medium hover:bg-green-800 disabled:opacity-50">
                      {isCompleting ? <><Loader2 className="mr-2 h-4 w-4 animate-spin" /> Processing...</> : <><CheckCircle className="mr-2 h-4 w-4" /> Mark as Handled</>}
                    </button>
                  )
                )}
              </div>
            </div>
          </div>
        )}

        {/* ── Audit Trail Tab ── */}
        {activeTab === 'audit' && (
          <div className="bg-white rounded-lg shadow-sm border border-gray-200">
            <div className="px-6 py-4 border-b border-gray-200 bg-gray-50 flex items-center justify-between">
              <div>
                <h2 className="text-lg font-semibold text-gray-900">Immutable Audit Trail</h2>
                <p className="text-xs text-gray-500 mt-1">Complete chronological record of all case actions</p>
              </div>
              <span className="text-sm text-gray-500">{(auditLogs || []).length} events</span>
            </div>
            <div className="px-6 py-6">
              {(!auditLogs || auditLogs.length === 0) ? (
                <div className="text-center py-12">
                  <FileText className="mx-auto h-12 w-12 text-gray-400 mb-3" />
                  <p className="text-sm text-gray-500">No audit events recorded yet.</p>
                </div>
              ) : (
                <ul className="-mb-8">
                  {auditLogs.map((log, idx) => {
                    const isExpanded = expandedLogs.has(log.audit_log_id);
                    const hasDetails = log.detail_payload && Object.keys(log.detail_payload).length > 0;
                    const isLast = idx === auditLogs.length - 1;
                    return (
                      <li key={log.audit_log_id}>
                        <div className="relative pb-8">
                          {!isLast && <span className="absolute top-5 left-5 -ml-px h-full w-0.5 bg-gray-200" />}
                          <div className="relative flex items-start space-x-3">
                            <div className="h-10 w-10 rounded-full flex items-center justify-center ring-8 ring-white bg-gray-100 border border-gray-200">
                              <Code className="h-5 w-5 text-gray-600" />
                            </div>
                            <div className="min-w-0 flex-1">
                              <div className="flex items-center justify-between">
                                <span className="text-sm font-semibold text-gray-900">{log.event_type?.replace(/_/g, ' ')}</span>
                                <div className="flex items-center space-x-2">
                                  <span className="text-xs text-gray-500 flex items-center">
                                    <Clock className="h-3 w-3 mr-1" />{new Date(log.timestamp).toLocaleString()}
                                  </span>
                                  {log.is_immutable && (
                                    <span className="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-gray-100 text-gray-700">
                                      <Shield className="h-3 w-3 mr-1" /> Immutable
                                    </span>
                                  )}
                                </div>
                              </div>
                              <p className="mt-0.5 text-sm text-gray-600">{log.description}</p>
                              {log.user_id && <p className="mt-1 text-xs text-gray-400">By: {log.user_id}</p>}
                              {hasDetails && (
                                <div className="mt-2">
                                  <button onClick={() => toggleLog(log.audit_log_id)}
                                    className="flex items-center text-sm text-blue-600 hover:text-blue-800">
                                    {isExpanded ? <ChevronDown className="h-4 w-4 mr-1" /> : <ChevronRight className="h-4 w-4 mr-1" />}
                                    {isExpanded ? 'Hide' : 'Show'} Details
                                  </button>
                                  {isExpanded && (
                                    <div className="mt-2 bg-gray-50 rounded-lg p-4 border border-gray-200">
                                      <pre className="text-xs text-gray-700 overflow-x-auto">
                                        {JSON.stringify(log.detail_payload, null, 2)}
                                      </pre>
                                    </div>
                                  )}
                                </div>
                              )}
                            </div>
                          </div>
                        </div>
                      </li>
                    );
                  })}
                </ul>
              )}
            </div>
          </div>
        )}
      </main>
    </div>
  );
}

// Workaround to use Clock icon inline with tab
function ClockIcon(props) {
  return <Clock {...props} />;
}
